name: Build & Deploy Microservices

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/docker-compose.yml'

jobs:
  build-and-deploy:
    name: Build and Deploy Microservices
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Configuration de Java
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # Étape 3: Construire chaque module Maven
      - name: Build all modules
        run: mvn clean package -DskipTests

      # Étape 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Étape 5: Build et Push Docker Images pour chaque microservice
      - name: Build & Push config-service
        working-directory: ./config-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/config-service:latest

      - name: Build & Push discovery-service
        working-directory: ./discovery-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-service:latest

      - name: Build & Push user-service
        working-directory: ./user-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

      - name: Build & Push role-service
        working-directory: ./role-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/role-service:latest
