# AMSA ASSURANCE
name: Build & Deploy Microservices

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/docker-compose.yml'

jobs:
  build-and-deploy:
    name: Build and Deploy Microservices
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Configuration de Java
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # Étape 3: Tester tous les modules Maven
      - name: Run Unit Tests
        run: mvn test --file pom.xml

      # Étape 4: Compiler et empaqueter tous les microservices
      - name: Build all services
        run: mvn clean package -DskipTests --file pom.xml

      # Étape 5: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Debug: Liste le contenu du répertoire de chaque service pour vérifier la présence de target/
      - name: List target directory in config-service
        run: ls -alh ./config-service/target

      - name: List target directory in discovery-service
        run: ls -alh ./discovery-service/target

      - name: List target directory in user-service
        run: ls -alh ./user-service/target

      - name: List target directory in role-service
        run: ls -alh ./role-service/target

      # Étape 6: Build et Push Docker Images pour chaque microservice
      - name: Build & Push config-service
        working-directory: ./config-service
        uses: docker/build-push-action@v2
        with:
          context: ./config-service
          file: ./config-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/config-service:config-service-v1

      - name: Build & Push discovery-service
        working-directory: ./discovery-service
        uses: docker/build-push-action@v2
        with:
          context: ./discovery-service
          file: ./discovery-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-service:discovery-service-v1

      - name: Build & Push paiement-service
        working-directory: ./user-service
        uses: docker/build-push-action@v2
        with:
          context: ./user-service
          file: ./user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:paiement-service-v1

      - name: Build & Push role-service
        working-directory: ./role-service
        uses: docker/build-push-action@v2
        with:
          context: ./role-service
          file: ./role-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/role-service:remboursement-service-v1
